//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataHandler.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wi16b087_Ex1_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public wi16b087_Ex1_Task()
        {
            this.wi16b087_Ex1_CrewMember = new HashSet<wi16b087_Ex1_CrewMember>();
        }
    
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int Priority { get; set; }
        public System.Guid TypeId { get; set; }
    
        public virtual wi16b087_Ex1_Type wi16b087_Ex1_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wi16b087_Ex1_CrewMember> wi16b087_Ex1_CrewMember { get; set; }
    }
}
